# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: debug-statements
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: detect-private-key
      - id: name-tests-test
        name: Tests should begin with test_*.py
        args: ["--pytest-test-first"]
      - id: check-merge-conflict
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
      - id: no-commit-to-branch
        args: [--branch, master]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v1.8.0
    hooks:
      - id: pyproject-fmt
        name: apply a consistent format to pyproject.toml files
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.5
    hooks:
      - id: poetry-check
        name: run 'poetry check' for checking pyproject.toml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        name: run `ruff` for Python linting
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: run `ruff format for Python formatting`
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    # need to run pre-commit install --hook-type commit-msg --hook-type pre-push
    hooks:
      - id: commitizen
        name: check conventional commits format
        args: [--allow-abort, --commit-msg-file]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.392.post0
    hooks:
      - id: pyright
        name: run `pyright`, a static type checker
        entry: poetry run pyright
        args: [task_list]
        language: system
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        name: run 'black' on Python code blocks in documentation files
        additional_dependencies:
          - black==23.11.0
        files: '\.md$'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: run 'prettier', an opinionated code formatter
        additional_dependencies:
          - prettier@3.1.0
        args: [--print-width=120, --prose-wrap=always]
        exclude: ".git"
